DROP DATABASE IF EXISTS GIMPACT;
CREATE DATABASE GIMPACT;
USE GIMPACT;

CREATE TABLE USER(
UNAME VARCHAR(20) PRIMARY KEY,
PASSWD VARCHAR(40)
);

CREATE TABLE MODEL(
ID INT PRIMARY KEY auto_increment,
NAME VARCHAR(20),
USER VARCHAR(20) REFERENCES USER(UNAME)
);

CREATE TABLE G_CHARACTER(
ID INT PRIMARY KEY auto_increment,
MODEL INT REFERENCES MODEL(ID),
NAME VARCHAR(20)
);

CREATE TABLE WEAPON(
ID INT PRIMARY KEY auto_increment,
G_CHARACTER INT REFERENCES G_CHARACTER(ID),
NAME VARCHAR(50),
LVL int
);

CREATE TABLE GOBLET(
ID INT PRIMARY KEY auto_increment,
G_CHARACTER INT REFERENCES G_CHARACTER(ID),
NAME VARCHAR(50),
LVL int,
statmain VARCHAR(10),
lvlmain int,
stat1 VARCHAR(10),
lvl1 int,
stat2 VARCHAR(10),
lvl2 int,
stat3 VARCHAR(10),
lvl3 int,
stat4 VARCHAR(10),
lvl4 int
);

CREATE TABLE FEATHER(
ID INT PRIMARY KEY auto_increment,
G_CHARACTER INT REFERENCES G_CHARACTER(ID),
NAME VARCHAR(50),
LVL int,
statmain VARCHAR(10),
lvlmain int,
stat1 VARCHAR(10),
lvl1 int,
stat2 VARCHAR(10),
lvl2 int,
stat3 VARCHAR(10),
lvl3 int,
stat4 VARCHAR(10),
lvl4 int
);

CREATE TABLE SANDS(
ID INT PRIMARY KEY auto_increment,
G_CHARACTER INT REFERENCES G_CHARACTER(ID),
NAME VARCHAR(50),
LVL int,
statmain VARCHAR(10),
lvlmain int,
stat1 VARCHAR(10),
lvl1 int,
stat2 VARCHAR(10),
lvl2 int,
stat3 VARCHAR(10),
lvl3 int,
stat4 VARCHAR(10),
lvl4 int
);

CREATE TABLE CROWN(
ID INT PRIMARY KEY auto_increment,
G_CHARACTER INT REFERENCES G_CHARACTER(ID),
NAME VARCHAR(50),
LVL int,
statmain VARCHAR(10),
lvlmain int,
stat1 VARCHAR(10),
lvl1 int,
stat2 VARCHAR(10),
lvl2 int,
stat3 VARCHAR(10),
lvl3 int,
stat4 VARCHAR(10),
lvl4 int
);

CREATE TABLE FLOWER(
ID INT PRIMARY KEY auto_increment,
G_CHARACTER INT REFERENCES G_CHARACTER(ID),
NAME VARCHAR(50),
LVL int,
statmain VARCHAR(10),
lvlmain int,
stat1 VARCHAR(10),
lvl1 int,
stat2 VARCHAR(10),
lvl2 int,
stat3 VARCHAR(10),
lvl3 int,
stat4 VARCHAR(10),
lvl4 int
);

CREATE TABLE STATS(
ID INT PRIMARY KEY auto_increment,
G_CHARACTER INT REFERENCES G_CHARACTER(ID),
LVLNORMAL INT,
LVLELEMENTAL INT,
LVLULTIMATE INT,
CONS INT
);